<?php

namespace Database\Seeders;

use App\Models\Influencer;
use Illuminate\Database\Seeder;

class InfluencerSeeder extends Seeder
{
    public function run(): void
    {
        $influencers = [
            [
                'name' => 'Bretman Rock',
                'slug' => 'bretman-rock',
                'bio' => 'Filipino-American creator known for beauty, fashion, comedy, lifestyle videos, and an unfiltered on-camera personality.',
                'profile_picture' => 'https://unavatar.io/instagram/bretmanrock',
                'instagram_link' => 'https://www.instagram.com/bretmanrock/',
                'youtube_link' => 'https://www.youtube.com/channel/UC3EFKdXAU99j3ppGgvTz7XQ',
                'tiktok_link' => 'https://www.tiktok.com/@bretmanrock',
                'facebook_link' => 'https://www.facebook.com/bretmanrock/',
            ],
            [
                'name' => 'Niana Guerrero',
                'slug' => 'niana-guerrero',
                'bio' => 'Filipino dancer and digital creator recognized for choreography, dance challenges, lifestyle videos, and family collaborations.',
                'profile_picture' => 'https://unavatar.io/instagram/nianaguerrero',
                'instagram_link' => 'https://www.instagram.com/nianaguerrero/',
                'youtube_link' => 'https://www.youtube.com/@nianaguerrero',
                'tiktok_link' => 'https://www.tiktok.com/@nianaguerrero',
                'facebook_link' => 'https://www.facebook.com/NianaGuerrero/',
            ],
            [
                'name' => 'Ranz Kyle',
                'slug' => 'ranz-kyle',
                'bio' => 'Filipino dancer and video creator known for energetic dance covers, challenges, music, and sibling collaborations.',
                'profile_picture' => 'https://unavatar.io/instagram/ranzkyle',
                'instagram_link' => 'https://www.instagram.com/ranzkyle/',
                'youtube_link' => 'https://www.youtube.com/@RanzKyle',
                'tiktok_link' => 'https://www.tiktok.com/@ranzkyle',
                'facebook_link' => 'https://www.facebook.com/RanzKyle/',
            ],
            [
                'name' => 'Cong TV',
                'slug' => 'cong-tv',
                'bio' => 'Filipino comedy and lifestyle vlogger, musician, gamer, and founder of the Team Payaman creator collective.',
                'profile_picture' => 'https://unavatar.io/instagram/thecongtv',
                'instagram_link' => 'https://www.instagram.com/thecongtv/',
                'youtube_link' => 'https://www.youtube.com/@CongTheVlogger',
                'tiktok_link' => 'https://www.tiktok.com/@thecongtv',
                'facebook_link' => null,
            ],
            [
                'name' => 'Viy Cortez',
                'slug' => 'viy-cortez',
                'bio' => 'Filipino lifestyle creator and entrepreneur whose content includes family vlogs, travel, challenges, and everyday experiences.',
                'profile_picture' => 'https://unavatar.io/instagram/viycortez',
                'instagram_link' => 'https://www.instagram.com/viycortez/',
                'youtube_link' => 'https://www.youtube.com/@ViyCortez',
                'tiktok_link' => 'https://www.tiktok.com/@viycortez',
                'facebook_link' => null,
            ],
            [
                'name' => 'Mimiyuuuh',
                'slug' => 'mimiyuuuh',
                'bio' => 'Filipino fashion graduate, comedian, and lifestyle creator known for expressive humor, fashion content, and candid vlogs.',
                'profile_picture' => 'https://unavatar.io/instagram/mimiyuuuh',
                'instagram_link' => 'https://www.instagram.com/mimiyuuuh/',
                'youtube_link' => 'https://www.youtube.com/@mimiyuuuh',
                'tiktok_link' => 'https://www.tiktok.com/@mimiyuuuh',
                'facebook_link' => 'https://www.facebook.com/mimiyuuuh/',
            ],
            [
                'name' => 'Wil Dasovich',
                'slug' => 'wil-dasovich',
                'bio' => 'Filipino-American travel and lifestyle vlogger known for cultural storytelling, personal challenges, and motivational content.',
                'profile_picture' => 'https://unavatar.io/instagram/wil_dasovich',
                'instagram_link' => 'https://www.instagram.com/wil_dasovich/',
                'youtube_link' => 'https://www.youtube.com/channel/UCSir19L_390tAg4IbCggvCg',
                'tiktok_link' => null,
                'facebook_link' => 'https://www.facebook.com/WilDasovich/',
            ],
            [
                'name' => 'Ninong Ry',
                'slug' => 'ninong-ry',
                'bio' => 'Filipino chef and food creator who combines practical cooking instruction, Filipino dishes, humor, and market knowledge.',
                'profile_picture' => 'https://unavatar.io/instagram/ninongry',
                'instagram_link' => 'https://www.instagram.com/ninongry/',
                'youtube_link' => 'https://www.youtube.com/@ninongry',
                'tiktok_link' => 'https://www.tiktok.com/@ninongry',
                'facebook_link' => 'https://www.facebook.com/NinongRy/',
            ],
            [
                'name' => 'Ivana Alawi',
                'slug' => 'ivana-alawi',
                'bio' => 'Filipino-Moroccan actress, model, entrepreneur, and lifestyle creator known for entertainment and family-oriented vlogs.',
                'profile_picture' => 'https://unavatar.io/instagram/ivanaalawi',
                'instagram_link' => 'https://www.instagram.com/ivanaalawi/',
                'youtube_link' => 'https://www.youtube.com/channel/UCypeLkg3Ne5-LIyiB41b1GQ',
                'tiktok_link' => null,
                'facebook_link' => 'https://www.facebook.com/ivanaalawi/',
            ],
            [
                'name' => 'Alex Gonzaga',
                'slug' => 'alex-gonzaga',
                'bio' => 'Filipino entertainer, comedian, host, author, and creator known for comedy sketches, challenges, and family vlogs.',
                'profile_picture' => 'https://unavatar.io/instagram/cathygonzaga',
                'instagram_link' => 'https://www.instagram.com/cathygonzaga/',
                'youtube_link' => 'https://www.youtube.com/channel/UC6N-9Wh0DYhDI8sQS7jwjVA',
                'tiktok_link' => null,
                'facebook_link' => 'https://www.facebook.com/AlexGonzagaOfficial/',
            ],
            [
                'name' => 'Abi Marquez',
                'slug' => 'abi-marquez',
                'bio' => 'Filipino food creator known as the Lumpia Queen, sharing approachable recipes, creative Filipino food, and culinary collaborations.',
                'profile_picture' => 'https://unavatar.io/instagram/abigailfmarquez',
                'instagram_link' => 'https://www.instagram.com/abigailfmarquez/',
                'youtube_link' => 'https://www.youtube.com/@AbiMarquez',
                'tiktok_link' => 'https://www.tiktok.com/@abigailfmarquez',
                'facebook_link' => null,
            ],
            [
                'name' => 'Toni Gonzaga',
                'slug' => 'toni-gonzaga',
                'bio' => 'Filipino host, actress, singer, producer, and digital creator whose channel features interviews and inspirational conversations.',
                'profile_picture' => 'https://unavatar.io/instagram/celestinegonzaga',
                'instagram_link' => 'https://www.instagram.com/celestinegonzaga/',
                'youtube_link' => 'https://www.youtube.com/@ToniGonzagaStudio',
                'tiktok_link' => null,
                'facebook_link' => null,
            ],
            [
                'name' => 'MrBeast',
                'slug' => 'mrbeast',
                'bio' => 'American creator and entrepreneur known for large-scale challenges, philanthropy-focused videos, competitions, and ambitious productions.',
                'profile_picture' => 'https://unavatar.io/instagram/mrbeast',
                'instagram_link' => 'https://www.instagram.com/mrbeast/',
                'youtube_link' => 'https://www.youtube.com/@MrBeast',
                'tiktok_link' => 'https://www.tiktok.com/@mrbeast',
                'facebook_link' => 'https://www.facebook.com/MrBeast6000/',
            ],
            [
                'name' => 'Marques Brownlee',
                'slug' => 'marques-brownlee',
                'bio' => 'American technology creator and podcaster known as MKBHD, producing detailed reviews of consumer electronics, cars, and emerging technology.',
                'profile_picture' => 'https://unavatar.io/instagram/mkbhd',
                'instagram_link' => 'https://www.instagram.com/mkbhd/',
                'youtube_link' => 'https://www.youtube.com/@mkbhd',
                'tiktok_link' => 'https://www.tiktok.com/@mkbhd',
                'facebook_link' => 'https://www.facebook.com/MKBHD/',
            ],
            [
                'name' => 'Emma Chamberlain',
                'slug' => 'emma-chamberlain',
                'bio' => 'American creator, podcaster, entrepreneur, and fashion personality known for candid lifestyle videos and a distinctive editing style.',
                'profile_picture' => 'https://unavatar.io/instagram/emmachamberlain',
                'instagram_link' => 'https://www.instagram.com/emmachamberlain/',
                'youtube_link' => 'https://www.youtube.com/@emmachamberlain',
                'tiktok_link' => 'https://www.tiktok.com/@emmachamberlain',
                'facebook_link' => null,
            ],
            [
                'name' => 'Mark Rober',
                'slug' => 'mark-rober',
                'bio' => 'American engineer, inventor, educator, and creator known for large-scale science experiments, engineering builds, and accessible STEM videos.',
                'profile_picture' => 'https://unavatar.io/instagram/markrober',
                'instagram_link' => 'https://www.instagram.com/markrober/',
                'youtube_link' => 'https://www.youtube.com/@MarkRober',
                'tiktok_link' => 'https://www.tiktok.com/@markrober',
                'facebook_link' => 'https://www.facebook.com/MarkRober/',
            ],
            [
                'name' => 'Ali Abdaal',
                'slug' => 'ali-abdaal',
                'bio' => 'British doctor-turned-creator, author, and entrepreneur focused on productivity, learning, sustainable work, and online business.',
                'profile_picture' => 'https://unavatar.io/instagram/aliabdaal',
                'instagram_link' => 'https://www.instagram.com/aliabdaal/',
                'youtube_link' => 'https://www.youtube.com/@aliabdaal',
                'tiktok_link' => 'https://www.tiktok.com/@aliabdaal',
                'facebook_link' => null,
            ],
            [
                'name' => 'Nas Daily',
                'slug' => 'nas-daily',
                'bio' => 'Video creator and entrepreneur known for short-form stories about people, cultures, communities, travel, and global ideas.',
                'profile_picture' => 'https://unavatar.io/instagram/nasdaily',
                'instagram_link' => 'https://www.instagram.com/nasdaily/',
                'youtube_link' => 'https://www.youtube.com/@NasDaily',
                'tiktok_link' => 'https://www.tiktok.com/@nasdaily',
                'facebook_link' => 'https://www.facebook.com/nasdaily/',
            ],
            [
                'name' => 'Ryan Trahan',
                'slug' => 'ryan-trahan',
                'bio' => 'American creator and entrepreneur known for inventive challenge series, travel storytelling, comedy, and charity-focused projects.',
                'profile_picture' => 'https://unavatar.io/instagram/ryantrahan',
                'instagram_link' => 'https://www.instagram.com/ryantrahan/',
                'youtube_link' => 'https://www.youtube.com/@ryan',
                'tiktok_link' => null,
                'facebook_link' => null,
            ],
            [
                'name' => 'Lilly Singh',
                'slug' => 'lilly-singh',
                'bio' => 'Canadian creator, comedian, actor, author, and producer known for sketches, motivational content, interviews, and entertainment projects.',
                'profile_picture' => 'https://unavatar.io/instagram/lilly',
                'instagram_link' => 'https://www.instagram.com/lilly/',
                'youtube_link' => 'https://www.youtube.com/@LillySingh',
                'tiktok_link' => 'https://www.tiktok.com/@lilly',
                'facebook_link' => 'https://www.facebook.com/LillySingh/',
            ],
            [
                'name' => 'Zach King',
                'slug' => 'zach-king',
                'bio' => 'American filmmaker and creator known for visual illusions, tightly edited short-form videos, and family-friendly digital storytelling.',
                'profile_picture' => 'https://unavatar.io/instagram/zachking',
                'instagram_link' => 'https://www.instagram.com/zachking/',
                'youtube_link' => 'https://www.youtube.com/@ZachKing',
                'tiktok_link' => 'https://www.tiktok.com/@zachking',
                'facebook_link' => 'https://www.facebook.com/ZachKingVine/',
            ],
            [
                'name' => 'Khaby Lame',
                'slug' => 'khaby-lame',
                'bio' => 'Senegalese-Italian creator known for silent comedy videos that humorously simplify overly complicated internet life hacks.',
                'profile_picture' => 'https://unavatar.io/instagram/khaby00',
                'instagram_link' => 'https://www.instagram.com/khaby00/',
                'youtube_link' => 'https://www.youtube.com/@khaby.lame',
                'tiktok_link' => 'https://www.tiktok.com/@khaby.lame',
                'facebook_link' => null,
            ],
            [
                'name' => 'Doctor Mike',
                'slug' => 'doctor-mike',
                'bio' => 'American physician and creator producing health education, medical reactions, interviews, fitness content, and myth-busting videos.',
                'profile_picture' => 'https://unavatar.io/instagram/doctor.mike',
                'instagram_link' => 'https://www.instagram.com/doctor.mike/',
                'youtube_link' => 'https://www.youtube.com/@DoctorMike',
                'tiktok_link' => 'https://www.tiktok.com/@doctor.mike',
                'facebook_link' => 'https://www.facebook.com/RealDoctorMike/',
            ],
            [
                'name' => 'Gordon Ramsay',
                'slug' => 'gordon-ramsay',
                'bio' => 'British chef, restaurateur, television personality, and digital creator sharing recipes, cooking instruction, reactions, and food entertainment.',
                'profile_picture' => 'https://unavatar.io/instagram/gordongram',
                'instagram_link' => 'https://www.instagram.com/gordongram/',
                'youtube_link' => 'https://www.youtube.com/@gordonramsay',
                'tiktok_link' => null,
                'facebook_link' => 'https://www.facebook.com/gordonramsay/',
            ],
        ];

        foreach ($influencers as $influencer) {
            Influencer::query()->updateOrCreate(
                ['slug' => $influencer['slug']],
                $influencer
            );
        }
    }
}
